# Generated by Django 4.0.1 on 2022-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restorent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cuisines', models.CharField(max_length=20)),
                ('averagecostoftwo', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('hastablebooking', models.BooleanField(default=False)),
                ('hasonlinedelivery', models.BooleanField()),
                ('aggregaterating', models.IntegerField()),
                ('ratingcolor', models.CharField(max_length=20)),
                ('ratingtext', models.CharField(max_length=20)),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
